names = ['Mike',
 'Sam',
 'James',
 'Adam',
 'Harry',
 'Alex',
 'John',
 'Luke',
 'Andy',
 'Ryan',
 'Ben',
 'Owen',
 'Fred',
 'Will',
 'Jamie',
 'Jake',
 'Sean',
 'Ewan',
 'Josh',
 'Tom',
 'Rob',
 'Jack',
 'Joe',
 'Max',
 'Matt',
 'Bill',
 'Liam',
 'Jay',
 'Chris',
 'Leo',
 'Henry',
 'Jen',
 'Grace',
 'Holly',
 'Eve',
 'Amy',
 'Daisy',
 'Zoe',
 'Sophie',
 'Mollie',
 'Lara',
 'Liz',
 'Sarah',
 'Lilly',
 'Alice',
 'Rachel',
 'Laura',
 'Leah',
 'Keira',
 'Julia',
 'Beth',
 'Emma',
 'Lily',
 'Chloe',
 'Emily',
 'Kate',
 'Anna',
 'Lucy',
 'Ella',
 'Sara',
 'Mary',
 'Rose',
 'Erin',
 'Steve',
 'Tim',
 'Carl',
 'Hugh',
 'Kim',
 'Jon',
 'Jane',
 'Scott',
 'Mark',
 'Colin',
 'Dan',
 'Phil',
 'Helen',
 'Ian',
 'Jeff']

verbs = ['posted',
 'wrote',
 'melted',
 'watered',
 'turned',
 'moved',
 'kissed',
 'served',
 'mailed',
 'fried',
 'entered',
 'labeled',
 'boiled',
 'dusted',
 'swallowed',
 'solved',
 'cut',
 'grated',
 'opened',
 'grabbed',
 'stroked',
 'hugged',
 'poured',
 'folded',
 'lifted',
 'locked',
 'painted',
 'watched',
 'toasted',
 'ironed',
 'mashed',
 'cleaned',
 'pulled',
 'examined',
 'peeled',
 'fed',
 'closed',
 'emptied',
 'visited',
 'fixed',
 'drove',
 'measured',
 'tidied',
 'dropped',
 'broke',
 'tasted',
 'filed',
 'built',
 'feed',
 'chewed',
 'polished',
 'washed',
 'drank',
 'sold',
 'jumped',
 'read',
 'wore',
 'pushed',
 'punched',
 'carried',
 'sniffed',
 'brushed',
 'combed',
 'fired',
 'cooked',
 'licked',
 'sliced',
 'dried',
 'baked',
 'gathered',
 'typed',
 'climbed',
 'stirred',
 'trimmed',
 'wiped',
 'chopped',
 'ate',
 'played']

stims = []

random.shuffle(names)
random.shuffle(verbs)

for v,n in zip(verbs, names):
	stims.append('The INANIMATE' + " " + v + " " + n)


stims = ['The ball bounced Ella',
 'The room tidied Beth',
 'The tomato sliced Ryan',
 'The book read Steve',
 'The floor cleaned Sean',
 'The orange peeled Scott',
 'The plans cancelled Ewan',
 'The meal cooked Josh',
 'The bread toasted Jon',
 'The hair combed Kim',
 'The tree hugged Bill',
 'The lolly sucked Phil',
 'The kettle boiled Anna',
 'The parcel mailed Matt',
 'The stew stirred Jay',
 'The museum visited Daisy',
 'The fence jumped Eve',
 'The milk sniffed Dan',
 'The bucket emptied John',
 'The paper cut Lily',
 'The icecream licked Rose',
 'The pill swallowed Erin',
 'The mirror kissed Liam',
 'The papers filed Jamie',
 'The jumper wore Harry',
 'The trolley pushed Tom',
 'The herbs chopped Joe',
 'The potatoes mashed Lucy',
 'The coins polished Hugh',
 'The folder carried Jeff',
 'The toffee chewed Sara',
 'The piano played Sophie',
 'The bushes trimmed Will',
 'The television watched Holly',
 'The puzzle solved Andy',
 'The picture painted Lara',
 'The card posted Ben',
 'The computer fixed Ian',
 'The sofa sold Kate',
 'The boat sailed Laura',
 'The table wiped Leah',
 'The fur stroked Leo',
 'The fork dropped Mary',
 'The towels dried Max',
 'The cake baked Mike',
 'The lever pulled Henry',
 'The house built Alice',
 'The car drove Jane',
 'The shelves dusted Jake',
 'The sheets folded Sarah',
 'The letter typed Colin',
 'The wall punched Emily',
 'The thread measured Chloe',
 'The wine poured Jack',
 'The door opened Rob',
 'The garden watered Adam',
 'The shirt ironed Jen',
 'The plate broke Rachel',
 'The dishes washed Tim',
 'The INANIMATE entered James',
 'The bill examined Carl',
 'The juice drank Grace',
 'The jar labeled Mark',
 'The chocolate melted Luke',
 'The rope grabbed Keira',
 'The eggs fried Emma',
 'The cheese grated Julia',
 'The window closed Fred',
 'The ham ate Helen',
 'The hill climbed Chris',
 'The box lifted Owen',
 'The dish served Alex',
 'The food tasted Amy',
 'The teeth brushed Lilly',
 'The handle turned Sam',
 'The wardrobe moved Liz',
 'The story wrote Mollie',
 'The chest locked Zoe']